version: '3'
services:
    
    mysql:
        image: mysql:5.7
        container_name: mysql
        networks: 
            - production-network
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
    api1:
        build:
            dockerfile: ./docker/python.dockerfile
            context: .
        image: python/api1
        container_name: api1
        ports:
            - "3000"
        networks: 
            - production-network
        depends_on:
            - "mysql"
    phpmyadmin:
        build:
            dockerfile: ./docker/python.dockerfile
            context: .
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        links:
            - mysql:db
        networks: 
            - production-network
        depends_on:
            - "mysql"

# MongoDB: https://hub.docker.com/_/mongo/
    mongo:
        image: mongo:3
        networks: 
            - production-network
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        networks: 
            - production-network
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
        image: graylog/graylog:3.2
        environment:
            # CHANGE ME (must be at least 16 characters)!
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        networks: 
            - production-network
        depends_on:
            - mongo
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - "9000:9000"
            # Syslog TCP
            - "1514:1514"
            # Syslog UDP
            - "1514:1514/udp"
            # GELF TCP
            - "12201:12201"
            # GELF UDP
            - "12201:12201/udp"

networks: 
    production-network:
        driver: bridge